### ISSUE TITLE
Hack to locate Python minor version

### ISSUE THREAD

**Issue by arthurmaciel** [cyclone-scheme/python#1]
Hi @justinethier! 

Would you mind testing this package? Only if you have Python 3 installed.

```shell
$ sudo apt install libpython3-dev # or similar
$ sudo winds install python
$ winds retrieve python
$ cd python/examples
$ pip install numpy
$ cyclone numpy.scm
$ ./numpy
```

The intention is to test (implicitly) the new hack to pass correct Python minor version to `(c-linker-options ...)`.

Thanks!

**Comment by justinethier** [comment]
Hey @arthurmaciel - here are the results of the above:

```
justin@justin-Latitude-5491:~/Documents/tmp/python/examples$ ./numpy 
<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11]
```

I did need to `apt install python3-dev` in order to install the winds `python` package.

Does that help? Anything further I can test?

**Comment by arthurmaciel** [comment]
It worked! Thanks! :)

Em dom, 26 de jun de 2022 19:59, Justin Ethier ***@***.***>
escreveu:

**Comment by justinethier** [comment]
Glad to help :+1:

**Comment by arthurmaciel** [comment]
It Is really useful that `(c-linker-options ...)` and `(c-compiler-options ...)` literally transfer their content to C, so we can use `pkg-config`, `python3-config` and others inside them. Thanks for making Cyclone nicer and easier to play with!

**Comment by justinethier** [comment]
No problem! Please let me know if you have any further suggestions for improvement :)
